<?php

$names = Array( 
"ASSAIRH Ayoub",      
"BREGEON Quentin",        
"BRIAND Marie",   
"BROCHOIRE Marin",        
"BROGNOLI Thomas",        
"BROHAN Alexis",      
"CORNILLEAU Florian",     
"DELAVAU Anaëlle",        
"DEVINEAU Valentin",      
"DUPLESSIS Quentin",      
"FÉLIX Matthieu",     
"GARA Aymeric",       
"GAZAUBE François",       
"GUEHO Frédéric",     
"GUILLET Mathis",     
"HERVAGAULT Killiann",        
"LAMBERT Damien",     
"MARTINEZ Hugo",      
"MASCOLO Nicola",     
"NICOLAS Maxime",     
"PILNIÈRE Paul Elie",     
"PIVETEAU Anatole",       
"SORIN Florian",      
"TEDESCO Florent",        
"YVARD Johnny",       
"AGAT Philippe",      
"AUVRAY Mélissa",     
"BICHOUX Thibault",       
"CHEVAL Clément",     
"DENIAUD Pierre Antoine",     
"FELON Allan",        
"GARAIOS Damien",     
"GAUTIER Thomas",     
"GICQUEL Cécile",     
"GUILLOTTE Vincent",      
"JUSTE Florian",      
"LALANDE Dylan",      
"LERAY Thomas",       
"LEVEQUE Valentin",       
"NAKKACHI Alexandre",     
"POUILLY Lucas",      
"ROCHA François",     
"ROTTHIER Axel",
);